apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: test-hydrator-helm
  name: test-hydrator-helm-helm-guestbook
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: helm-guestbook
    release: test-hydrator-helm
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: test-hydrator-helm
  name: test-hydrator-helm-helm-guestbook
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-guestbook
      release: test-hydrator-helm
  template:
    metadata:
      labels:
        app: helm-guestbook
        release: test-hydrator-helm
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: helm-guestbook
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
